env.jenkins="jenkins"
API_BASE_URL="https://api-dev.telkomdigitalsolution.co"
API_CATALOG_BASE_URL="https://catalog-api-dev.telkomdigitalsolution.co"
Authorization="Basic dGVsa29tZGlnaXRhbHNvbHV0aW9uZDN2OjY5NTg0OWRlLTlmYWEtNGJjMy05ZmIzLTA2NjAzNDQzNWM1OQ=="
CIPHER_KEY="dGVsa29tdGRzY3VzdG9tZXI6Z"
TOPIC_TDS_USER_CC="tds_user_cc_develop"
TOPIC_TDS_USER_GENERAL="tds_general_develop"
TOPIC_TDS_CATALOG_PROMO="tds_catalog_develop_promo"
CI="true"
MYAPP_FLAVOR="true"
MYAPP_RELEASE_STORE_FILE="my-release-key.keystore"
MYAPP_RELEASE_KEY_ALIAS="my-key-alias"
MYAPP_RELEASE_STORE_PASSWORD="tdsam123"
MYAPP_RELEASE_KEY_PASSWORD="tdsam123"
DB_URL4="url44"
