#!/bin/bash
echo "Menyiapkan Installasi Web server"
sudo apt-get update
echo "Melakukan Installasi Webserver"
sudo apt-get install -y nginx php php-mysql

wget https://github.com/sdcilsy/sosial-media/archive/master.zip
sudo rm /var/www/html/*
sudo rm -R /var/www/html/*
sudo mv sosial-media-master/* /var/www/html
echo "Setup selesai"
